### ISSUE TITLE
publish wheels

### ISSUE THREAD

**Issue by dimbleby** [aws-samples/sample-python-helper-aws-appconfig#18]
It is better for the ecosystem for package owners to publish wheels as well as source distributions - else everyone who installs your package must do it themselves.  That is slower, and might conceivably go wrong.  Better for the publisher to build the wheel once and for all.

I did not find a release pipeline in this repository or I would have submitted a pull request.

Since you are using poetry: I believe that `poetry build` and/or `poetry publish` will build and publish both wheels and sdists by default.

**Comment by jamesoff** [comment]
Thanks for the feedback! I'll take a look at adding that to the release process (and/or sorting a pipeline out).
