### ISSUE TITLE
update_config can cause BadRequestException

### ISSUE THREAD

**Issue by jrobbins-LiveData** [aws-samples/sample-python-helper-aws-appconfig#2]
The [early return](https://github.com/aws-samples/sample-python-helper-aws-appconfig/blob/f1b2fdf39ff675d98df644b9304065dad5afe34d/appconfig_helper/appconfig_helper.py#L155) in `update_config` (to deal with empty content when the config hasn't changed) 

```
        if content == b"":
            return False
```

results in this error
```
BadRequestException('An error occurred (BadRequestException) when calling the GetLatestConfiguration operation: Request too early')
```

if the next call to `update_config` happens soon enough after this call.  

The reason the exception is raised by `get_latest_configuration` is that this ealy return fails to update the variable (`self._last_update_time`) used to guard against calling before the negotiated minimum poll set via the `RequiredMinimumPollIntervalInSeconds` arg to `start_configuration_session`.

Changing the code to

```
            if content == b"":
                self._last_update_time = time.time()
                return False
```

would fix this problem.

**Comment by jamesoff** [comment]
Thanks for the report!

**Comment by jrobbins-LiveData** [comment]
You're welcome!  Thanks for the fix (along with an updated unit test!)
