### ISSUE TITLE
Need to cut a new version to pip

### ISSUE THREAD

**Issue by jchorl** [aws-samples/sample-python-helper-aws-appconfig#4]
Hi!

I hit this:
https://github.com/aws-samples/sample-python-helper-aws-appconfig/issues/2

Fresh install:
```shell
$ docker run -it --rm python:3 bash
# pip install sample-helper-aws-appconfig
# cat /usr/local/lib/python3.10/site-packages/appconfig_helper/version.py 
VERSION = "2.0.0"
```

Notably, it doesn't contain https://github.com/aws-samples/sample-python-helper-aws-appconfig/commit/8a2a67e573d08a4c1ebc4428414e2345b8e5ba44

However, cloning and checking out `v2.0.1` does in fact contain https://github.com/aws-samples/sample-python-helper-aws-appconfig/commit/8a2a67e573d08a4c1ebc4428414e2345b8e5ba44.

Mind pushing a new version to pip?

**Comment by jamesoff** [comment]
Whoops, thanks for pointing that out. I'll cut a new version and upload it, which will have to be 2.0.2.

**Comment by jamesoff** [comment]
Done (hopefully!), let me know if that's fixed it for you, and apologies for the bad release.
