### ISSUE TITLE
Start a new session if token expired

### ISSUE THREAD

**Issue by BiochemLouis** [aws-samples/sample-python-helper-aws-appconfig#5]
The helper as it is right now is not able to recover from expired token (>24h old).

I don't think there is a way to refresh token other than starting a new session and using this initial token.

I would like opinions about possible recovery/prevention methods:

First thought was a recovery method by adding a try/except block around [update_config's `get_latest_configuration()` call](https://github.com/aws-samples/sample-python-helper-aws-appconfig/blob/f94d9e198ffcf8c42e14e1ce574c6e7e02bfbd41/appconfig_helper/appconfig_helper.py#L147) to catch invalid tokens and start a fresh session.

```py
        try: 
            response = self._client.get_latest_configuration(
                ConfigurationToken=self._next_config_token
            )
        except BadRequestException:
            self.start_session()  # get a fresh session, might need to close old one not sure
            response = self._client.get_latest_configuration(
                ConfigurationToken=self._next_config_token
            )
```

Second option would be preventive by adding a time check similar to the [if time since update < polling time](https://github.com/aws-samples/sample-python-helper-aws-appconfig/blob/f94d9e198ffcf8c42e14e1ce574c6e7e02bfbd41/appconfig_helper/appconfig_helper.py#L139), but for time since update over 24h.

```py
        if (
            self._next_config_token is None
            or time.time() - self._last_update_time >= 86400
        ):
            self.start_session()
```

I know this is a rare case, but it happened to me in testing where the service was deployed and testers took over 24h to get to testing, which caused the service to be DOA according to them.

**Comment by jamesoff** [comment]
My preference would be the former, it feels more Pythonic (Ask Forgiveness Not Permission) and would also cover any case where the token was invalid for any other reason.

You're right that there's no way to refresh an expired token, so the only option is to create a new session.
